global:
  scrape_interval: 10s
  evaluation_interval: 5s

rule_files:
  # - "/etc/prometheus/targets/blackbox.rules.yml"

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: /alertmanager
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]


  - job_name: "sql_exporter"
    static_configs:
      - targets: ['sql-exporter:9237']
groups:
  - name: dba
    rules:
      - record: sql_table_cache_hitrate
        expr: (sql_pg_statio_user_tables{col="heap_blks_hit"} - ignoring(col) sql_pg_statio_user_tables{col="heap_blks_read"}) / ignoring(col) sql_pg_statio_user_tables{col="heap_blks_hit"} * 100 >= 0
      - record: sql_table_index_usage_rate
        expr: sql_pg_stat_user_tables{col="idx_scan"} / ignoring(col) (sql_pg_stat_user_tables{col="seq_scan"} + ignoring(col) sql_pg_stat_user_tables{col="idx_scan"}) * 100 >= 0
      - record: sql_index_cache_hitrate
        expr: (sql_pg_statio_user_tables{col="idx_blks_hit"} - ignoring(col) sql_pg_statio_user_tables{col="idx_blks_read"}) / ignoring(col) sql_pg_statio_user_tables{col="idx_blks_hit"} * 100 >= 0
      - record: sql_running_queries
        expr: sum(sql_connections{state="active"}) without(state)