global:
  scrape_interval: 10s
  evaluation_interval: 5s

rule_files:
  # - "/etc/prometheus/targets/blackbox.rules.yml"

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: /alertmanager
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "http"
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 192.168.0.21:84
        labels:
          environment: prod
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
      - source_labels: [__param_target]
        target_label: instance

  - job_name: "blackbox_exporter"
    metrics_path: /probe
    params:
      module:
        - http_2xx # Look for a HTTP 200 response.
        - icmp
    scrape_interval: 3s
    scrape_timeout: 2s
    static_configs:
      - targets:
          ###############################################################################
          # services
          ###############################################################################
          - http://192.168.0.21:83/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115 # The blackbox exporter's real hostname:port.