global:
  scrape_interval: 10s
  evaluation_interval: 5s

rule_files:
  # - "/etc/prometheus/targets/blackbox.rules.yml"

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: /alertmanager
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]


  - job_name: "sql_exporter"
    static_configs:
      - targets: ['sql-exporter:9237']
