---
#jobs:
#  - name: "duplicates_overtimes"
#    interval: 1m
#    engines:
#      - alias: "monitoring_duplicates"
#        type: "postgres"
#        host: "localhost"
#        port: 5432
#        db: "jarvis_test"
#        user: "jarvis_user"
#        vault_key: "jarvis_test"
#        connection_timeout: 60
#    queries:
#      - name: jarvis_duplicates_overtimes
#        help: "Дубликаты при заведении овертайм"
#        labels:
#          - username
#        values:
#          - endtime
#        query: |
#          SELECT
#            user_name,
#            starttime,
#            endtime
#          FROM overtime_users T1
#          WHERE (SELECT COUNT(*)
#          FROM overtime_users T2
#          WHERE T1.user_name = T2.user_name) > 1
#          ORDER BY starttime
jobs:
  # each job needs a unique name, it's used for logging and as an default label
  - name: "duplicates_overtime"
    # interval defined the pause between the runs of this job
    interval: '1m'
    # connections is an array of connection URLs
    # each query will be executed on each connection
    connections:
      - 'postgresql://jarvis_user:jarvis_test@postgres:5433/jarvis_test?sslmode=disable'
    # startup_sql is an array of SQL statements
    # each statements is executed once after connecting
    # queries is a map of Metric/Query mappings
    queries:
      # name is prefied with sql_ and used as the metric name
      - name: "running_queries"
        # help is a requirement of the Prometheus default registry, currently not
        # used by the Prometheus server. Important: Must be the same for all metrics
        # with the same name!
        help: "Number of running queries"
        # Labels is an array of columns which will be used as additional labels.
        # Must be the same for all metrics with the same name!
        # All labels columns should be of type text, varchar or string
        labels:
          - "datname"
          - "usename"
        # Values is an array of columns used as metric values. All values should be
        # of type float
        values:
          - "count"
        # Query is the SQL query that is run unalterted on the each of the connections
        # for this job
        query:  |
          SELECT 
                    user_name,
                    starttime,
                    endtime
                  FROM overtime_users T1
                  WHERE (SELECT COUNT(*)
                  FROM overtime_users T2
                  WHERE T1.user_name = T2.user_name) > 1
                  ORDER BY starttime
        # Consider the query failed if it returns zero rows
        allow_zero_rows: false

  - name: "master-nodes"
    interval: '1m'
    connections:
      - 'postgresql://jarvis_user:jarvis_test@postgres/postgres?sslmode=disable'
    queries:
        - name: "pg_settings"
          help: "Values of PostgreSQL runtime settings"
          labels:
            - "name"
          values:
            - "setting"
          query:  |
            SELECT
              name::text,
              setting::float
            FROM pg_settings
            WHERE
              vartype IN ('integer','real')
            UNION
            SELECT
              name::text,
              CASE setting WHEN 't' THEN 1::float ELSE 0::float END
            FROM pg_settings
            WHERE
              vartype = 'bool';
        - name: "pg_stat_database"
          help: "PostgreSQL Database stats"
          labels:
            - "datname"
          values:
            - "numbackends"
            - "xact_commit"
            - "xact_rollback"
            - "blks_read"
            - "blks_hit"
            - "tup_returned"
            - "tup_fetched"
            - "tup_inserted"
            - "tup_updated"
            - "tup_deleted"
            - "conflicts"
            - "temp_files"
            - "deadlocks"
            - "blk_read_time"
            - "blk_write_time"
          query:  |
            SELECT
              datname::text,
              numbackends::float,
              xact_commit::float,
              xact_rollback::float,
              blks_read::float,
              blks_hit::float,
              tup_returned::float,
              tup_fetched::float,
              tup_inserted::float,
              tup_updated::float,
              tup_deleted::float,
              conflicts::float,
              temp_files::float,
              deadlocks::float,
              blk_read_time::float,
              blk_write_time::float
            FROM pg_stat_database;
        - name: "connections"
          help: "Number of connections in different states"
          labels:
            - "datname"
            - "usename"
            - "state"
          values:
            - "count"
          query:  |
            SELECT
              datname::text,
              usename::text,
              state::text,
              COUNT(state)::float AS count
            FROM pg_stat_activity
            GROUP BY datname, usename, state;
        - name: "db_sizes"
          help: "Database Sizes"
          labels:
            - "dbname"
          values:
            - "dbsize"
          query:  |
            SELECT
              datname::text AS dbname,
              pg_database_size(datname)::float AS dbsize
            FROM pg_database;
        - name: "replication_senders_count"
          help: "Replication Senders connected"
          values:
            - "count"
          query:  |
            SELECT
              COUNT(*)::float AS count
            FROM
              pg_stat_replication;
        - name: "pg_is_in_recovery"
          help: "Bool flag if the node is in recovery"
          values:
            - "case"
          query:  |
            SELECT
              CASE pg_is_in_recovery() WHEN 't' THEN 1::float ELSE 0::float END;
      

  - name: "per-db-stats"
    interval: '15m'
    keepalive: false
    connections:
      - 'postgresql://jarvis_user:jarvis_test@postgres:5433/postgres?sslmode=disable'
    queries:
      - name: "pg_stat_user_tables"
        help: "Table stats"
        labels:
          - "schemaname"
          - "relname"
        values:
          - "seq_scan"
          - "seq_tup_read"
          - "idx_scan"
          - "idx_tup_fetch"
          - "n_tup_ins"
          - "n_tup_upd"
          - "n_tup_del"
          - "n_tup_hot_upd"
          - "n_live_tup"
          - "n_dead_tup"
          - "vacuum_count"
          - "autovacuum_count"
          - "analyze_count"
          - "autoanalyze_count"
        query: |
          SELECT
            schemaname::text
          , relname::text
          , seq_scan::float
          , seq_tup_read::float
          , idx_scan::float
          , idx_tup_fetch::float
          , n_tup_ins::float
          , n_tup_upd::float
          , n_tup_del::float
          , n_tup_hot_upd::float
          , n_live_tup::float
          , n_dead_tup::float
          , vacuum_count::float
          , autovacuum_count::float
          , analyze_count::float
          , autoanalyze_count::float
          FROM pg_stat_user_tables;
      - name: "pg_statio_user_tables"
        help: "IO Stats"
        labels:
          - "schemaname"
          - "relname"
        values:
          - "heap_blks_read"
          - "heap_blks_hit"
          - "idx_blks_read"
          - "idx_blks_hit"
        query: |
          SELECT
            schemaname::text
          , relname::text
          , heap_blks_read::float
          , heap_blks_hit::float
          , idx_blks_read::float
          , idx_blks_hit::float
          FROM pg_statio_user_tables;
