---
jobs:
  - name: "duplicates_overtimes"
    interval: 1m
    engines:
      - alias: "monitoring_duplicates"
        type: "postgres"
        host: "localhost"
        port: 5432
        db: "jarvis_test"
        user: "jarvis_user"
        vault_key: "jarvis_test"
        connection_timeout: 60
    queries:
      - name: jarvis_duplicates_overtimes
        help: "Дубликаты при заведении овертайм"
        labels:
          - username
        values:
          - endtime
        query: |
          SELECT 
            user_name,
            starttime,
            endtime
          FROM overtime_users T1
          WHERE (SELECT COUNT(*)
          FROM overtime_users T2
          WHERE T1.user_name = T2.user_name) > 1
          ORDER BY starttime
